site_name: Universal Language Model Distillation

plugins:
  - mkdocstrings

theme:
  name: gitbook
  highlightjs: true
  hljs_languages:
    - python

nav:
    - Introduction: 'index.md'
    - ğŸš€ Tutorials:
      - Get started: 'tutorials/index.md'
      - Distillation using the CLI: 'tutorials/cli.md'
      - Distillation from Python: 'tutorials/cli.md'
    - ğŸ§‘â€ğŸ’» How-to guides:
      - Distil your own model: 'tutorials/index.md'
      - Distil with MLM smoothing: 'tutorials/index.md'
      - Distil from two teacher models: 'tutorials/index.md'
      - Domain-adapted distillation: 'tutorials/index.md'
      - Mitigate stereotyping with constraints: 'tutorials/index.md'
    - ğŸ¤– API reference:
      - Tokenization: 'tutorials/index.md'
      - Distillation: 'tutorials/index.md'
      - Training: 'tutorials/index.md'
    - ğŸ›° Further reading:
      - Paper: 'tutorials/index.md'
